name = "Geo"
uuid = "64103927-62c7-4d13-95e7-06861cfc1e9c"
authors = ["Brian D. Klahn <briandk@virginia.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
